// Code generated by "stringer -type=BidirectionalSearch"; DO NOT EDIT.

package goel

import "fmt"

const _BidirectionalSearch_name = "BidirectionalFalseBidrectionalFirstBidrectionalSecondBidrectionalBoth"

var _BidirectionalSearch_index = [...]uint8{0, 18, 35, 53, 69}

func (i BidirectionalSearch) String() string {
	if i < 0 || i >= BidirectionalSearch(len(_BidirectionalSearch_index)-1) {
		return fmt.Sprintf("BidirectionalSearch(%d)", i)
	}
	return _BidirectionalSearch_name[_BidirectionalSearch_index[i]:_BidirectionalSearch_index[i+1]]
}
